<?php
require_once 'navbar_index.phtml'
?>


<div class="index-body p-5">

    <div class="d-flex">
        <div class="w-50 p-2">
            <div class="d-flex align-items-center justify-content-center text-center bgFourth textFirst border-1 border-dark shadow rounded p-3" style="min-height:200px">
                Conheça ClientControll – O CRM Gratuito!
                <br>
                Desde 2022 atendendo a necessidade da sua empresa para gerenciamento dos seus clientes
            </div>
        </div>
        <div class="w-50 p-2">
            <div class="d-flex align-items-center justify-content-center text-center bgFourth textFirst border-1 border-dark shadow rounded p-3" style="min-height:200px">
                Faça seu cadastro e utilize a nossa ferramenta gratuita
            </div>
        </div>
    </div>
</div>