<nav class="navIndex py-2">

    <ul class="nav container-xxl" id="myTab" role="tablist">
        <li class="nav-item mr-5" role="presentation">
            <a href="/" class="nav-link text-uppercase">Home</a>
        </li>
        <li class="nav-item mr-5" role="presentation">
            <a href="/login" class="nav-link nav-link-index text-uppercase">
                <i class="fa-solid fa-arrow-right-to-bracket"></i>
                Fazer Login</button>
            </a>
        </li>
        <li class="nav-item mr-5" role="presentation">
            <a href="/cadastrar" class="nav-link text-uppercase">Cadastre-se</a>
        </li>
    </ul>
</nav>