<section class="hv-100 wv-100 bgFifth">
    <?php
    require_once 'navbar.phtml';
    ?>

    <div class="container-fluid p-3 d-flex justify-content-center align-items-center">
        <div class="bgFirst col-10 p-2 rounded shadow">
            <div class="col-12">
                <h5 class="text-center fw-bold m-0 my-3">
                    Registre um novo Cliente
                </h5>
            </div>
            <?php if ($this->view->registerReturn == "RegisteredSuccessfully") { ?>
                <div class="col-12 mt-1">
                    <div class="w-100 bg-success text-white rounded p-1 text-center bg-gradient fw-bold"><span>Cliente cadastrado com sucesso</span></div>
                </div>
            <?php } ?>
            <?php if ($this->view->registerReturn == "repeatedCPF") { ?>
                <div class="col-12 mt-1">
                    <div class="w-100 bg-danger rounded p-1 text-white text-center bg-gradient fw-bold"><span>CPF já cadastrado</span></div>
                </div>
            <?php } ?>
            <form class="col-12 d-flex flex-wrap" method="POST" action="/customerRegistration">
                <div class="mb-3 px-2 col-12">
                    <label for="name" class="form-label">Nome:</label>
                    <input type="text" class="form-control" id="name" name="name" required>
                </div>

                <div class="mb-3 px-2 col-3">
                    <label for="birth_date" class="form-label">Data de Nascimento:</label>
                    <input type="date" class="form-control" id="birth_date" name="birth_date" required>
                </div>

                <div class="mb-3 px-2 col-9">
                    <label for="email" class="form-label">E-mail:</label>
                    <input type="email" class="form-control" id="email" name="email" required>
                </div>

                <div class="mb-3 px-2 col-6">
                    <label for="cpf" class="form-label">CPF:</label>
                    <input type="text" class="form-control" id="cpf" name="cpf" required>
                </div>

                <div class="mb-3 px-2 col-6">
                    <label for="phone" class="form-label">Telefone:</label>
                    <input type="text" class="form-control" id="phone" name="phone">
                </div>


                <div class="col-12 px-2 d-flex aling-content-center justify-content-end">
                    <button type="button" class="btn btn-danger mx-2" data-bs-toggle="modal" data-bs-target="#cancel_registration">
                        Cancelar
                    </button>

                    <button type="submit" class="btn btn-success">Cadastrar Cliente</button>
                </div>
            </form>
        </div>
    </div>
    
</section>

<div class="modal fade" id="cancel_registration" tabindex="-1" aria-labelledby="cancel_registrationLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content bgFifth">
            <div class="modal-header">
                <h1 class="modal-title fs-5 text-white" id="cancel_registrationLabel">Deseja retornar a listagem de cliente?</h1>
                <button type="button" class="btn-close bgFirst" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Fechar</button>
                <a href="/customers" class="btn btn-danger">Retornar</a>
            </div>
        </div>
    </div>
</div>

<script src="/js/customers.js"></script>