<nav class="navbar navIndexUser navbar-dark bg-dark">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#navbarUser" aria-controls="navbarUser">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="/indexUser">
            <img src="../img/logo.png" style="max-height: 50px">
        </a>
        <div class="offcanvas offcanvas-start text-bg-dark navbarUser w-auto" tabindex="-1" id="navbarUser" aria-labelledby="navbarLabel">
            <div class="offcanvas-header">
                <h5 class="offcanvas-title" id="navbarLabel">LOGO</h5>
                <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
            </div>
            <div class="offcanvas-body d-flex flex-column align-content-center justify-content-between">

                <div>
                    <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
                        <li class="navbar-side nav-item">
                            <a class="nav-link" aria-current="page" href="/indexUser">
                                <div class="div-icon-navbar d-flex align-content-center justify-content-center">
                                    <i class="fa-solid fa-chart-line"></i>
                                </div> Home
                            </a>
                        </li>
                        <li class="navbar-side nav-item mt-2">
                            <a class="nav-link" href="/customers">
                                <div class="div-icon-navbar d-flex align-content-center justify-content-center">
                                <i class="fa-solid fa-gear"></i>
                                </div>
                                Clientes
                            </a>
                        </li>
                    </ul>
                </div>

                <div class="navbar-side nav-item mt-2">
                    <a class="nav-link" href="/logoff">
                        <div class="div-icon-navbar d-flex align-content-center justify-content-center">
                            <i class="fa-solid fa-power-off"></i>
                        </div>
                        Sair
                    </a>
                </div>

            </div>
        </div>
    </div>
</nav>