<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>

	<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
	<script src="https://kit.fontawesome.com/7fd336d5ad.js" crossorigin="anonymous"></script>
	<link rel="stylesheet" type="text/css" href="/css/style.css">

	<script src="/js/bootstrap.bundle.min.js"></script>

	<!-- LIBS -->
	<!-- Alertify -->
	<link rel="stylesheet" href="/libs/sweetalert2/dist/sweetalert2.min.css" />
	<script src="/libs/sweetalert2/dist/sweetalert2.all.min.js"></script>
	<script src="/libs/sweetalert2/dist/sweetalert2.min.js"></script>

</head>

<body>
	<?= $this->content() ?>
</body>

</html>